/** The compact owner compiles this finite inventory before its final worker.
 * This is statement transport only; row arguments and accepted authority are
 * independently bound by the private maintenance and record plans. */
export const compactTerminalSql = Object.freeze([
  'PRAGMA main.schema_version',
  'PRAGMA temp.schema_version',
  'PRAGMA main.data_version',
  'PRAGMA data_version',
  'SELECT MAX(version) AS version FROM schema_migrations',
  "SELECT value FROM app_meta WHERE key='revision'",
  'SELECT value FROM app_meta WHERE key=?',
  'SELECT value FROM main.app_meta WHERE key=?',
  'SELECT length(CAST(value AS BLOB)) AS bytes FROM app_meta WHERE key=?',
  'SELECT length(CAST(value AS BLOB)) AS bytes, CASE WHEN length(CAST(value AS BLOB))<=? THEN value END AS value FROM app_meta WHERE key=?',
  'SELECT sha256,kind FROM source_files WHERE id=?',
  'SELECT sha256,kind FROM main.source_files WHERE id=?',
  'SELECT length(CAST(details_json AS BLOB)) AS bytes FROM source_files WHERE id=?',
  'SELECT kind,sha256 FROM main.source_files WHERE id=?',
  'SELECT details_json FROM source_files WHERE id=?',
  'SELECT CAST(rowid AS TEXT) AS __rowid,* FROM main.source_files WHERE id=?',
  'UPDATE main.source_files SET details_json=? WHERE id=? AND details_json IS ?',
  'SELECT COUNT(*) AS n FROM __record_changed',
  'SELECT entity,record_id FROM __record_changed',
  'SELECT entity,record_id FROM temp.__record_changed',
  'SELECT * FROM __record_changed ORDER BY entity,record_id',
  'SELECT 1 FROM temp.__record_changed LIMIT 1',
  "SELECT 1 FROM sqlite_temp_master WHERE type='table' AND name='__record_changed'",
  "SELECT 1 FROM sqlite_temp_schema WHERE type IN ('table','view') AND (lower(name) IN ('source_files','app_meta','__record_state','__record_current','__record_versions','__record_transactions','__record_fields') OR lower(name) GLOB '__record_intake_lookup_*') LIMIT 1",
  "SELECT 1 FROM sqlite_temp_schema WHERE type='table' AND name='__intake_lookup_authorities'",
  'SELECT total_changes() AS n',
  'SELECT total_changes() AS writes',
  'SELECT * FROM __record_state WHERE singleton=1',
  'SELECT commit_json FROM __record_transactions WHERE sequence=?',
  'SELECT * FROM __record_transactions WHERE sequence=?',
  'SELECT * FROM __record_transactions WHERE operation_id=?',
  'SELECT version_id FROM __record_current WHERE entity=? AND record_id=?',
  'SELECT * FROM __record_versions WHERE version_id=?',
  'SELECT v.* FROM __record_current c JOIN __record_versions v ON v.version_id=c.version_id WHERE c.entity=? AND c.record_id=?',
  'SELECT v.version_id,v.deleted FROM __record_current c JOIN __record_versions v ON v.version_id=c.version_id WHERE c.entity=? AND c.record_id=?',
  'SELECT 1 FROM __record_current c JOIN __record_versions v ON v.version_id=c.version_id WHERE c.entity=? AND c.record_id=? AND v.version_id=? AND v.contents_json IS ? AND v.deleted=0',
  'INSERT INTO app_meta(key,value) VALUES(?,?)',
  'INSERT INTO app_meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',
  "INSERT OR IGNORE INTO app_meta(key,value) VALUES('clinical_review_revision',(SELECT value FROM app_meta WHERE key='revision'))",
  "INSERT INTO app_meta(key,value) VALUES('curation_revision',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",
  'INSERT INTO __record_versions VALUES(?,?,?,?,?,?,?,?,?,?,?)',
  'INSERT INTO __record_current VALUES(?,?,?) ON CONFLICT(entity,record_id) DO UPDATE SET version_id=excluded.version_id',
  'INSERT INTO __record_transactions VALUES(?,?,?,?,?)',
  'INSERT OR REPLACE INTO __record_state VALUES(1,?,?,?,?,?)',
]);
export const compactTerminalBigIntSql = Object.freeze([
  'SELECT total_changes() AS count',
  'PRAGMA temp.schema_version',
  'SELECT total_changes() AS changes,(SELECT data_version FROM pragma_data_version) AS external,(SELECT schema_version FROM pragma_schema_version) AS schema',
]);
export const compactTerminalExecutions = Object.freeze([
  'BEGIN IMMEDIATE',
  'COMMIT',
  'ROLLBACK',
  "UPDATE app_meta SET value=CAST(value AS INTEGER)+1 WHERE key='revision'",
]);
