import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { format, resolveConfig } from 'prettier';
import { renderBrandPng as renderPng } from './brand-raster.ts';

const SCRIPT_DIRECTORY = dirname(fileURLToPath(import.meta.url));
const SOURCE_ROOT = join(SCRIPT_DIRECTORY, '..');
const LOGO_SOURCE = join(SOURCE_ROOT, 'assets', 'brand', 'logo.svg');
const TOKENS_SOURCE = join(SOURCE_ROOT, 'app', 'tokens.css');
const COMPONENT_OUTPUT = join(SOURCE_ROOT, 'app', 'components', 'BrandMark.generated.tsx');
const PUBLIC_DIRECTORY = join(SOURCE_ROOT, 'public');
const TAGLINE = 'Your circus, your monkeys, all under one tent.';
const COLOR_SLOTS = [
  'brand-pink',
  'brand-pink-fold',
  'brand-blue',
  'brand-blue-fold',
  'brand-lavender',
  'brand-lavender-fold',
  'brand-butter',
  'brand-butter-fold',
  'brand-highlight',
] as const;
const COLOR_SLOT_SET = new Set<string>(COLOR_SLOTS);

type Palette = Record<(typeof COLOR_SLOTS)[number] | 'background', string>;
type GeneratedFile = { path: string; contents: string | Buffer };

function cssBlock(css: string, selector: string): string {
  const selectorOffset = css.indexOf(selector);
  if (selectorOffset < 0) throw new Error(`Missing palette selector: ${selector}`);
  const openingBrace = css.indexOf('{', selectorOffset);
  const closingBrace = css.indexOf('}', openingBrace);
  if (openingBrace < 0 || closingBrace < 0)
    throw new Error(`Invalid palette selector: ${selector}`);
  return css.slice(openingBrace + 1, closingBrace);
}

function readPalette(css: string, selector: string): Palette {
  const block = cssBlock(css, selector);
  return Object.fromEntries(
    [...COLOR_SLOTS, 'background'].map((slot) => {
      const match = block.match(new RegExp(`--${slot}:\\s*(#[0-9a-fA-F]{6})\\s*;`));
      if (!match) throw new Error(`Missing --${slot} in ${selector}`);
      return [slot, match[1].toLowerCase()];
    }),
  ) as Palette;
}

function validateLogo(source: string): void {
  if (!source.startsWith('<svg ') || !source.trimEnd().endsWith('</svg>')) {
    throw new Error('Canonical logo must contain one SVG root');
  }
  if (/<(?:script|foreignObject|image|use|style)\b|\son[a-z]+\s*=|(?:href|src)\s*=/i.test(source)) {
    throw new Error('Canonical logo contains unsupported executable or external SVG content');
  }
  const tags = [...source.matchAll(/<\/?([A-Za-z][\w:-]*)\b/g)].map((match) => match[1]);
  const unsupported = tags.find((tag) => tag !== 'svg' && tag !== 'path');
  if (unsupported) throw new Error(`Canonical logo contains unsupported <${unsupported}> content`);
  const usedSlots = [...source.matchAll(/var\(--([a-z-]+)\)/g)].map((match) => match[1]);
  if (usedSlots.length === 0 || usedSlots.some((slot) => !COLOR_SLOT_SET.has(slot))) {
    throw new Error('Canonical logo must use only the approved brand color slots');
  }
  for (const slot of COLOR_SLOTS) {
    if (!usedSlots.includes(slot)) throw new Error(`Canonical logo does not use --${slot}`);
  }
}

function resolveColors(source: string, palette: Palette): string {
  return source.replace(/var\(--([a-z-]+)\)/g, (_match, slot: keyof Palette) => palette[slot]);
}

function standaloneSvg(source: string, palette: Palette, variant: string): string {
  const titled = source.replace(
    /<svg ([^>]+)>/,
    `<svg $1 role="img" aria-labelledby="circus-health-logo-title">\n  <title id="circus-health-logo-title">${TAGLINE}</title>`,
  );
  return `<!-- Generated by scripts/generate-brand-assets.ts from assets/brand/logo.svg (${variant}). -->\n${resolveColors(titled, palette)}`;
}

async function reactComponent(source: string): Promise<string> {
  const paths = source
    .split('\n')
    .filter((line) => line.trimStart().startsWith('<path'))
    .map((line) =>
      line.replace('stroke-width=', 'strokeWidth=').replace('stroke-linecap=', 'strokeLinecap='),
    )
    .join('\n');
  const viewBox = source.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error('Canonical logo is missing its viewBox');

  const component = `// Generated by scripts/generate-brand-assets.ts from assets/brand/logo.svg. Do not edit.\nimport { useId } from 'react';\nimport type { SVGProps } from 'react';\n\nexport type BrandMarkProps = Omit<SVGProps<SVGSVGElement>, 'children'> & {\n  decorative?: boolean;\n  title?: string;\n};\n\nexport function BrandMark({\n  decorative = false,\n  title = '${TAGLINE}',\n  role,\n  'aria-label': ariaLabel,\n  'aria-labelledby': ariaLabelledBy,\n  'aria-hidden': ariaHidden,\n  ...props\n}: BrandMarkProps) {\n  const titleId = useId();\n  const hasProvidedName = ariaLabel != null || ariaLabelledBy != null;\n\n  return (\n    <svg\n      {...props}\n      viewBox="${viewBox}"\n      role={decorative ? undefined : (role ?? 'img')}\n      aria-label={decorative ? undefined : ariaLabel}\n      aria-labelledby={\n        decorative ? undefined : (ariaLabelledBy ?? (ariaLabel == null ? titleId : undefined))\n      }\n      aria-hidden={decorative ? true : ariaHidden}\n      focusable="false"\n    >\n      {!decorative && !hasProvidedName ? <title id={titleId}>{title}</title> : null}\n${paths}\n    </svg>\n  );\n}\n`;
  return format(component, {
    ...(await resolveConfig(COMPONENT_OUTPUT)),
    filepath: COMPONENT_OUTPUT,
  });
}

function pngDimensions(png: Buffer): [number, number] {
  const signature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  if (!png.subarray(0, 8).equals(signature)) throw new Error('Rasterizer returned an invalid PNG');
  return [png.readUInt32BE(16), png.readUInt32BE(20)];
}

function createIco(entries: Array<{ size: number; png: Buffer }>): Buffer {
  const directorySize = 6 + entries.length * 16;
  const header = Buffer.alloc(directorySize);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(entries.length, 4);
  let offset = directorySize;
  entries.forEach(({ size, png }, index) => {
    const entryOffset = 6 + index * 16;
    header.writeUInt8(size === 256 ? 0 : size, entryOffset);
    header.writeUInt8(size === 256 ? 0 : size, entryOffset + 1);
    header.writeUInt8(0, entryOffset + 2);
    header.writeUInt8(0, entryOffset + 3);
    header.writeUInt16LE(1, entryOffset + 4);
    header.writeUInt16LE(32, entryOffset + 6);
    header.writeUInt32LE(png.length, entryOffset + 8);
    header.writeUInt32LE(offset, entryOffset + 12);
    offset += png.length;
  });
  return Buffer.concat([header, ...entries.map(({ png }) => png)]);
}

function manifest(background: string): string {
  return `${JSON.stringify(
    {
      name: 'Circus Health',
      short_name: 'Circus Health',
      icons: [
        { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
        { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      ],
      theme_color: background,
      background_color: background,
    },
    null,
    2,
  )}\n`;
}

function digest(contents: string | Buffer): string {
  return createHash('sha256').update(contents).digest('hex').slice(0, 12);
}

async function outputs(): Promise<GeneratedFile[]> {
  const [logoSource, tokens] = await Promise.all([
    readFile(LOGO_SOURCE, 'utf8'),
    readFile(TOKENS_SOURCE, 'utf8'),
  ]);
  validateLogo(logoSource);
  const dark = readPalette(tokens, ":root[data-theme='dark']");
  const light = readPalette(tokens, ":root[data-theme='light']");
  const darkSvg = standaloneSvg(logoSource, dark, 'dark');
  const lightSvg = standaloneSvg(logoSource, light, 'light');
  const faviconDarkSvg = standaloneSvg(logoSource, dark, 'dark favicon');
  const faviconLightSvg = standaloneSvg(logoSource, light, 'light favicon');
  const icoEntries = await Promise.all(
    [16, 32, 48].map(async (size) => ({
      size,
      png: await renderPng(faviconDarkSvg, size),
    })),
  );
  const appleTouch = await renderPng(darkSvg, 180, dark.background, 0.78);
  const icon192 = await renderPng(darkSvg, 192, dark.background, 0.78);
  const icon512 = await renderPng(darkSvg, 512, dark.background, 0.78);

  for (const [expected, png] of [
    [180, appleTouch],
    [192, icon192],
    [512, icon512],
    ...icoEntries.map(({ size, png }) => [size, png] as const),
  ] as const) {
    const [width, height] = pngDimensions(png);
    if (width !== expected || height !== expected) {
      throw new Error(`Expected ${expected}x${expected} PNG, received ${width}x${height}`);
    }
  }

  return [
    { path: COMPONENT_OUTPUT, contents: await reactComponent(logoSource) },
    { path: join(PUBLIC_DIRECTORY, 'logo.svg'), contents: lightSvg },
    { path: join(PUBLIC_DIRECTORY, 'favicon.svg'), contents: faviconDarkSvg },
    { path: join(PUBLIC_DIRECTORY, 'favicon-dark.svg'), contents: faviconDarkSvg },
    { path: join(PUBLIC_DIRECTORY, 'favicon-light.svg'), contents: faviconLightSvg },
    { path: join(PUBLIC_DIRECTORY, 'favicon.ico'), contents: createIco(icoEntries) },
    { path: join(PUBLIC_DIRECTORY, 'apple-touch-icon.png'), contents: appleTouch },
    { path: join(PUBLIC_DIRECTORY, 'icon-192.png'), contents: icon192 },
    { path: join(PUBLIC_DIRECTORY, 'icon-512.png'), contents: icon512 },
    { path: join(PUBLIC_DIRECTORY, 'site.webmanifest'), contents: manifest(dark.background) },
  ];
}

async function main(): Promise<void> {
  const check = process.argv.slice(2).includes('--check');
  const unexpectedArguments = process.argv.slice(2).filter((argument) => argument !== '--check');
  if (unexpectedArguments.length > 0) {
    throw new Error(`Unknown arguments: ${unexpectedArguments.join(', ')}`);
  }
  const generated = await outputs();
  const stale: string[] = [];
  for (const output of generated) {
    if (check) {
      const existing = await readFile(output.path).catch(() => null);
      const expected = Buffer.isBuffer(output.contents)
        ? output.contents
        : Buffer.from(output.contents);
      if (!existing?.equals(expected)) stale.push(output.path.slice(SOURCE_ROOT.length + 1));
    } else {
      await writeFile(output.path, output.contents);
      console.log(
        `generated ${output.path.slice(SOURCE_ROOT.length + 1)} (${digest(output.contents)})`,
      );
    }
  }
  if (stale.length > 0) {
    throw new Error(
      `Brand assets are missing or stale:\n${stale.map((path) => `  ${path}`).join('\n')}`,
    );
  }
  if (check) console.log(`brand assets are current (${generated.length} files)`);
}

await main();
