import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { deflateSync } from 'node:zlib';
import { createCanvas } from '@napi-rs/canvas';
import type { IntakeIdentityReview } from '../shared/intake-identity.ts';
import type { IntakeClinicalMapping, IntakeEvidenceLocator } from '../shared/intake.ts';

export const qualificationPerson = 'Fictional Qualification Person';
export const qualificationBirthDate = '1982-04-17';
export const qualificationSourceSystem = 'Fictional Qualification System';
export type QualificationStage = 'extracted' | 'accepted';
export type QualificationScenario = 'quick' | 'long';
export interface QualificationAnswer {
  page: number;
  format: 'dense' | 'scan';
  marker: string;
  kind: 'observation' | 'medication' | 'procedure';
  fields: Partial<IntakeClinicalMapping>;
}
export function answersForQualification(
  scenario: QualificationScenario,
): readonly QualificationAnswer[] {
  return Array.from({ length: scenario === 'quick' ? 64 : 400 }, (_, index) => {
    const rows = scenario === 'quick' ? 16 : 4;
    const page = Math.floor(index / rows) + 1;
    const row = index % rows;
    const marker = `FXP${page}R${String(row + 1).padStart(2, '0')}`;
    const date = `2026-${String(Math.floor((page - 1) / 28) + 1).padStart(2, '0')}-${String(((page - 1) % 28) + 1).padStart(2, '0')}`;
    const kind =
      scenario === 'quick' || row < 2 ? 'observation' : row === 2 ? 'medication' : 'procedure';
    const fields: Partial<IntakeClinicalMapping> =
      kind === 'observation'
        ? {
            testLabel: marker,
            eventKind: 'performed',
            status: 'final',
            observationCategory: 'laboratory',
            specimen: '',
            method: '',
            date,
            valueText:
              row % 7 === 0 ? `<${(0.01 * page).toFixed(2)}` : (page + row * 0.17).toFixed(2),
            unit: row % 3 === 0 ? 'mg/dL' : row % 3 === 1 ? 'U/L' : 'mmol/L',
            referenceText: '0.01 - 9.99',
          }
        : kind === 'medication'
          ? {
              medicationName: marker,
              medicationKind: 'order',
              eventKind: 'order',
              dateRole: 'recorded',
              date,
              doseText: `${page + 1} mg`,
              route: 'oral',
              frequency: 'once daily',
              startDate: '',
              endDate: '',
            }
          : {
              procedureLabel: marker,
              procedureCategory: 'imaging',
              date,
              eventKind: 'performed',
              status: 'completed',
            };
    return {
      page,
      format: page % 2 ? 'dense' : 'scan',
      marker,
      kind,
      fields: { ...fields, subject: 'self', sourceSystem: qualificationSourceSystem },
    };
  });
}
export const qualificationAnswers = answersForQualification('quick');
const escaped = (value: string) => value.replace(/[\\()]/g, '\\$&');
const text = (value: string, x: number, y: number, size: number) =>
  `BT /F1 ${size} Tf ${x} ${y} Td (${escaped(value)}) Tj ET\n`;

/** The oracle is never supplied as model instructions. Even-numbered pages have
 * only painted pixels, without hidden text/OCR. All generated bytes stay outside Git. */
export function writeProviderQualificationPdf(
  path: string,
  scenario: QualificationScenario = 'quick',
) {
  const answers = answersForQualification(scenario);
  const pages = Math.max(...answers.map((answer) => answer.page));
  const chunks: Buffer[] = [];
  const offsets = [0];
  let bytes = 0;
  const output = (value: string | Buffer) => {
    const buffer = typeof value === 'string' ? Buffer.from(value) : value;
    chunks.push(buffer);
    bytes += buffer.length;
  };
  const object = (id: number, value: string | (() => void)) => {
    offsets[id] = bytes;
    output(`${id} 0 obj\n`);
    if (typeof value === 'string') output(value);
    else value();
    output('\nendobj\n');
  };
  const stream = (id: number, value: Buffer, dictionary = '') =>
    object(id, () => {
      output(`<< /Length ${value.length} ${dictionary} >>\nstream\n`);
      output(value);
      output('\nendstream');
    });
  output('%PDF-1.4\n');
  object(1, '<< /Type /Catalog /Pages 2 0 R >>');
  object(
    2,
    `<< /Type /Pages /Count ${pages} /Kids [${Array.from({ length: pages }, (_, i) => `${3 + i * 3} 0 R`).join(' ')}] >>`,
  );
  for (let page = 1; page <= pages; page++) {
    const rows = answers.filter((answer) => answer.page === page);
    const scan = page % 2 === 0;
    const id = 3 + (page - 1) * 3;
    const lines: Array<[string, number, number, number]> = [
      ['FICTIONAL CLINICAL QUALIFICATION REPORT', 30, 758, 14],
      [`Original page ${page} of ${pages}. Patient: ${qualificationPerson}.`, 30, 736, 9],
      [
        `Patient DOB: ${qualificationBirthDate}. The named patient is the profile owner (Self).`,
        30,
        716,
        9,
      ],
      [
        `Issuing software/system: ${qualificationSourceSystem}. Entirely invented data.`,
        30,
        696,
        9,
      ],
      [
        'Each FX marker is a distinct literal clinical label; preserve it without expanding it.',
        30,
        676,
        9,
      ],
    ];
    if (scenario === 'quick') {
      lines.push(
        [
          'No external patient/record IDs or terminology codes supplied. FX markers are labels only.',
          30,
          228,
          8,
        ],
        [
          `Performed laboratory event date: ${rows[0].fields.date}. All results are final.`,
          30,
          656,
          9,
        ],
        [
          'Analyte marker                 Result           Unit              Reference interval',
          30,
          626,
          10,
        ],
        ...rows.map((row, index): [string, number, number, number] => [
          `${row.marker.padEnd(31)}${row.fields.valueText!.padEnd(17)}${row.fields.unit!.padEnd(18)}${row.fields.referenceText}`,
          30,
          602 - index * 21,
          9,
        ]),
      );
    } else {
      rows.forEach((row, index) => {
        const y = 630 - index * 90;
        lines.push([`${row.kind.toUpperCase()} ${row.marker}`, 30, y, 11]);
        if (row.kind === 'observation')
          lines.push(
            [
              `Performed laboratory date: ${row.fields.date}. Result: ${row.fields.valueText}; Unit: ${row.fields.unit}.`,
              30,
              y - 20,
              10,
            ],
            [
              `Reference interval: ${row.fields.referenceText}. Final laboratory observation.`,
              30,
              y - 38,
              10,
            ],
          );
        else if (row.kind === 'medication')
          lines.push(
            [
              `Medication ORDER recorded ${row.fields.date}: ${row.marker}, ${row.fields.doseText}, oral, once daily.`,
              30,
              y - 20,
              9,
            ],
            [
              'This is an order, not reported use, dispensing or administration. No start/end date supplied.',
              30,
              y - 38,
              8,
            ],
          );
        else
          lines.push(
            [
              `Performed imaging procedure ${row.marker} on ${row.fields.date}; status: completed.`,
              30,
              y - 20,
              9,
            ],
            ['This procedure was performed, not merely ordered or recommended.', 30, y - 38, 9],
          );
      });
    }
    lines.push(
      [
        'No specimen, method, collection time, timezone or abnormality interpretation supplied.',
        30,
        210,
        8,
      ],
      ['Preserve the less-than signs and decimal precision exactly as printed.', 30, 192, 8],
      [
        'Administrative footer: generated independently for software qualification only.',
        30,
        64,
        8,
      ],
    );
    object(
      id,
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 << /Type /Font /Subtype /Type1 /BaseFont /Courier >> >> ${scan ? `/XObject << /Scan ${id + 2} 0 R >>` : ''} >> /Contents ${id + 1} 0 R >>`,
    );
    if (scan) {
      const canvas = createCanvas(1224, 1584);
      const context = canvas.getContext('2d');
      context.fillStyle = '#faf9f4';
      context.fillRect(0, 0, canvas.width, canvas.height);
      context.translate(1, 1);
      context.rotate(0.001);
      context.fillStyle = '#161616';
      for (const [value, x, y, size] of lines) {
        context.font = `${size * 2}px monospace`;
        context.fillText(value, x * 2, (792 - y) * 2);
      }
      stream(id + 1, deflateSync('q 612 0 0 792 0 0 cm /Scan Do Q\n'), '/Filter /FlateDecode');
      stream(
        id + 2,
        canvas.toBuffer('image/jpeg', 90),
        '/Type /XObject /Subtype /Image /Width 1224 /Height 1584 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode',
      );
      canvas.width = canvas.height = 1;
    } else {
      stream(
        id + 1,
        deflateSync(lines.map(([value, x, y, size]) => text(value, x, y, size)).join('')),
        '/Filter /FlateDecode',
      );
      object(id + 2, 'null');
    }
  }
  const xref = bytes;
  output(
    `xref\n0 ${offsets.length}\n0000000000 65535 f \n${offsets
      .slice(1)
      .map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`)
      .join('')}trailer\n<< /Size ${offsets.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`,
  );
  const pdf = Buffer.concat(chunks);
  writeFileSync(path, pdf, { flag: 'wx', mode: 0o600 });
  return {
    sha256: createHash('sha256').update(pdf).digest('hex'),
    bytes: pdf.length,
    scenario,
    pages,
    expectedRecords: answers.length,
    expectedKinds: [...new Set(answers.map((answer) => answer.kind))],
  };
}

export interface QualificationRecord {
  id: string;
  kind: string;
  mapping: IntakeClinicalMapping;
  evidence?: IntakeEvidenceLocator[];
  identityReview?: Pick<IntakeIdentityReview, 'status' | 'conflicts' | 'evidencedIdentity'>;
  /** Only attached when reading actual accepted public observation projections. */
  observationProjection?: {
    value: number | null;
    comparator: string | null;
    datePrecision: string;
  };
}
const normalized = (value: string) => value.replace(/\s+/g, '').replaceAll('−', '-');
const empty = (value: unknown) =>
  value === undefined ||
  value === null ||
  (typeof value === 'string' && value.trim() === '') ||
  (Array.isArray(value) && value.length === 0);
const enumFields = new Set([
  'kind',
  'subject',
  'eventKind',
  'status',
  'observationCategory',
  'medicationKind',
  'procedureCategory',
  'dateRole',
]);
const sameLiteral = (value: unknown, expected: string, field: string) =>
  expected === ''
    ? empty(value) && !Array.isArray(value)
    : typeof value === 'string' &&
      (enumFields.has(field)
        ? normalized(value).toLowerCase() === normalized(expected).toLowerCase()
        : normalized(value) === normalized(expected));
const clinicalFields = [
  'kind',
  'label',
  'date',
  'subject',
  'status',
  'sourceRecordId',
  'sourceSystem',
  'eventKind',
  'observationCategory',
  'documentCategory',
  'visitSpecialty',
  'testLabel',
  'valueText',
  'unit',
  'referenceText',
  'code',
  'codeSystem',
  'specimen',
  'method',
  'medicationName',
  'doseText',
  'route',
  'frequency',
  'medicationKind',
  'dateRole',
  'startDate',
  'endDate',
  'procedureLabel',
  'procedureCategory',
  'documentTitle',
  'documentDate',
  'opticalPrescription',
  'text',
  'assets',
  'uncertainties',
] as const satisfies readonly (keyof IntakeClinicalMapping)[];
const fieldSet = new Set<string>(clinicalFields);

/** Every known mapping field is expected, explicitly absent, or a narrowly allowed
 * host default. Unknown nonempty fields also fail. Host-transcribed payload text
 * and generated envelope titles are not separate clinical document assertions. */
function mappingMismatches(
  mapping: IntakeClinicalMapping,
  answer: QualificationAnswer,
  originalId: string,
  stage: QualificationStage,
) {
  const fields = Object.entries(answer.fields)
    .filter(
      ([field, value]) =>
        !(stage === 'extracted' && field === 'subject' && mapping.subject === 'unknown') &&
        !sameLiteral(mapping[field as keyof IntakeClinicalMapping], value as string, field),
    )
    .map(([field]) => field);
  const raw = mapping as Record<string, unknown>;
  const origins =
    raw.mappingOrigins && typeof raw.mappingOrigins === 'object'
      ? (raw.mappingOrigins as Record<string, unknown>)
      : {};
  for (const field of clinicalFields) {
    if (Object.hasOwn(answer.fields, field)) continue;
    const value = mapping[field];
    let allowed = empty(value) && !Array.isArray(value);
    if (field === 'kind') allowed ||= sameLiteral(value, answer.kind, field);
    else if (['label', 'testLabel', 'medicationName', 'procedureLabel'].includes(field))
      allowed ||= sameLiteral(value, answer.marker, field);
    else if (field === 'medicationKind') allowed ||= sameLiteral(value, 'unknown', field);
    else if (field === 'procedureCategory') allowed ||= sameLiteral(value, 'unspecified', field);
    else if (field === 'dateRole') allowed ||= sameLiteral(value, 'recorded', field);
    else if (field === 'documentDate') allowed ||= sameLiteral(value, answer.fields.date!, field);
    else if (field === 'documentTitle')
      allowed ||=
        typeof value === 'string' &&
        (origins.documentTitle === 'envelope' || sameLiteral(value, answer.marker, field));
    else if (field === 'text') allowed ||= typeof value === 'string' && origins.text === 'payload';
    else if (field === 'assets')
      allowed =
        value === undefined ||
        value === null ||
        (Array.isArray(value) && value.every((id) => id === originalId));
    else if (field === 'uncertainties')
      allowed =
        value === undefined || value === null || (Array.isArray(value) && value.length === 0);
    if (!allowed) fields.push(field);
  }
  for (const [field, value] of Object.entries(raw))
    if (!fieldSet.has(field) && field !== 'mappingOrigins' && !empty(value)) fields.push(field);
  return fields;
}

/** A marker's expected fixture page is not evidence. Require exactly one original
 * page in the returned locator and the original file URL; broad ranges fail. */
export function exactQualificationPage(
  evidence: IntakeEvidenceLocator,
  originalId: string,
): number | null {
  if (!evidence.contentUrl) return null;
  let url: URL;
  try {
    url = new URL(evidence.contentUrl, 'http://qualification.invalid');
  } catch {
    return null;
  }
  if (url.origin !== 'http://qualification.invalid') return null;
  const source = url.pathname.match(
    /^\/api\/(?:profiles\/[^/]+\/)?sources\/([^/]+)\/content$/,
  )?.[1];
  try {
    if (!source || decodeURIComponent(source) !== originalId) return null;
  } catch {
    return null;
  }
  const locator = evidence.locator;
  if (/\b(?:maybe|possibly|uncertain|approximately|approx|between|either)\b|\?/i.test(locator))
    return null;
  if (
    /\b(?:pages?|pp?\.?)[\s:#]*\d+\s*(?:[-–—,;+&/]|\b(?:to|through|thru|and|or)\b)\s*\d+/i.test(
      locator,
    )
  )
    return null;
  const matches = [...locator.matchAll(/\b(?:pages?|pp?\.?)[\s:#]*(\d+)\b/gi)].map((match) =>
    Number(match[1]),
  );
  const fragment = url.hash.match(/^#page=(\d+)$/);
  if (fragment) matches.push(Number(fragment[1]));
  const pages = [...new Set(matches)];
  return pages.length === 1 && pages[0] > 0 ? pages[0] : null;
}

/** Independent known-answer reconciliation over actual returned records.
 * Extraction may retain an explicit unknown patient pending human review. That
 * is not permission to accept: accepted projections must identify saved Self.
 * Every literal clinical field and original-page locator uses the same oracle. */
export function gradeProviderQualification(
  records: readonly QualificationRecord[],
  originalId: string,
  scenario: QualificationScenario = 'quick',
  stage: QualificationStage = 'accepted',
) {
  const answers = answersForQualification(scenario);
  const missing: string[] = [];
  const duplicate: string[] = [];
  const mismatches: Array<{ marker: string; fields: string[] }> = [];
  const matched = new Set<string>();
  const seenIds = new Set<string>();
  const duplicateIds = records
    .filter((record) => {
      const seen = seenIds.has(record.id);
      seenIds.add(record.id);
      return seen;
    })
    .map((record) => record.id);
  for (const answer of answers) {
    const matches = records.filter(
      (record) =>
        record.kind === answer.kind &&
        new RegExp(`\\b${answer.marker}\\b`).test(
          (record.kind === 'observation'
            ? record.mapping.testLabel
            : record.kind === 'medication'
              ? record.mapping.medicationName
              : record.mapping.procedureLabel) ??
            record.mapping.label ??
            '',
        ),
    );
    if (!matches.length) {
      missing.push(answer.marker);
      continue;
    }
    if (matches.length !== 1) duplicate.push(answer.marker);
    for (const record of matches) {
      matched.add(record.id);
      const fields = mappingMismatches(record.mapping, answer, originalId, stage);
      const identity = record.identityReview;
      if (
        identity &&
        (identity.status === 'conflict' ||
          identity.conflicts.length ||
          (identity.evidencedIdentity.fullName !== undefined &&
            identity.evidencedIdentity.fullName.replace(/\s+/g, ' ').trim() !==
              qualificationPerson) ||
          (identity.evidencedIdentity.birthDate !== undefined &&
            identity.evidencedIdentity.birthDate !== qualificationBirthDate))
      )
        fields.push('subjectIdentity');
      if (record.observationProjection) {
        const literal = answer.fields.valueText;
        const decimal = typeof literal === 'string' ? /^(<)?(\d+(?:\.\d+)?)$/.exec(literal) : null;
        const expectedValue = decimal ? Number(decimal[2]) : null;
        const expectedComparator = decimal?.[1] ?? null;
        if (record.observationProjection.value !== expectedValue) fields.push('publicNumericValue');
        if (record.observationProjection.comparator !== expectedComparator)
          fields.push('publicComparator');
        if (record.observationProjection.datePrecision !== 'day')
          fields.push('publicDatePrecision');
      }
      const locators = (record.evidence ?? []).filter(
        (item) => item.label === 'Original source' || item.contentUrl?.includes('/sources/'),
      );
      if (
        !locators.length ||
        locators.some((item) => exactQualificationPage(item, originalId) !== answer.page)
      )
        fields.push('originalPageProvenance');
      if (fields.length) mismatches.push({ marker: answer.marker, fields });
    }
  }
  const unexpected = records.filter((record) => !matched.has(record.id)).map((record) => record.id);
  const correct = answers.filter(
    (answer) =>
      !missing.includes(answer.marker) &&
      !duplicate.includes(answer.marker) &&
      !mismatches.some((mismatch) => mismatch.marker === answer.marker),
  );
  return {
    passed:
      !missing.length &&
      !duplicate.length &&
      !duplicateIds.length &&
      !mismatches.length &&
      !unexpected.length,
    stage,
    expectedRecords: answers.length,
    observedRecords: records.length,
    exactRecords: correct.length,
    pages: [...new Set(answers.map((answer) => answer.page))].map((page) => ({
      page,
      format: page % 2 ? 'dense' : 'scan',
      expected: answers.filter((answer) => answer.page === page).length,
      exact: correct.filter((answer) => answer.page === page).length,
    })),
    missing,
    duplicate,
    duplicateIds,
    mismatches,
    unexpected,
  };
}
