// UI demonstration literals, not imported clinical evidence. Keep this scenario
// synthetic; never replace its names or measurements with a real patient record.
import type { ImportReviewRecord, ImportReviewReport } from './ImportReviewPresentation';

export const initialReports: ImportReviewReport[] = [
  {
    id: 'dexa',
    source: 'Fictional Scan Center',
    sourceSuggested: true,
    sourceConfirmed: false,
    reportType: 'DEXA scan',
    date: 'Mar 14, 2026',
    subject: { label: 'Rowan', evidence: 'named', confirmed: true },
  },
  {
    id: 'vision',
    source: 'Juniper Optometry',
    sourceConfirmed: true,
    reportType: 'Eyeglass prescription',
    date: 'Feb 9, 2026',
    subject: {
      label: 'Rowan',
      evidence: 'missing',
      confirmed: false,
      identityStatus: 'confirmation_required',
      identityMessage: 'The report identifies Rowan Ellis. Confirm the retained evidence.',
      scopeReady: true,
      offeredSelfFields: { fullName: 'Rowan Ellis', birthDate: '1988-04-12' },
      selfDisplayName: 'Rowan',
    },
  },
  {
    id: 'visit',
    source: 'Cedar Clinic',
    sourceConfirmed: true,
    reportType: 'Annual visit',
    date: 'Mar 3, 2026',
    subject: { label: 'Rowan', evidence: 'named', confirmed: true },
  },
  {
    id: 'labs',
    source: 'Mesa Labs',
    sourceConfirmed: true,
    reportType: 'Lab report',
    date: 'Jan 12, 2026',
    subject: { label: 'Rowan', evidence: 'named', confirmed: true },
  },
];

export const initialRecords: ImportReviewRecord[] = [
  {
    id: 'height',
    reportId: 'dexa',
    kind: 'Test results',
    label: 'Intake height',
    originalLabel: 'HEIGHT',
    value: '64.0',
    unit: 'in',
    status: 'review',
    eligible: false,
  },
  {
    id: 'weight',
    reportId: 'dexa',
    kind: 'Test results',
    label: 'Intake weight',
    originalLabel: 'TOTAL WEIGHT',
    value: '147.2',
    unit: 'lb',
    status: 'review',
    eligible: false,
    relatedMatch: { value: '146.8 lb', source: 'Cedar Clinic', date: 'Mar 14, 2026' },
  },
  {
    id: 'fat',
    reportId: 'dexa',
    kind: 'Test results',
    label: 'Total body fat',
    originalLabel: 'BODY FAT %',
    value: '28.4',
    unit: '%',
    status: 'review',
    eligible: false,
  },
  {
    id: 'lean',
    reportId: 'dexa',
    kind: 'Test results',
    label: 'Lean tissue',
    originalLabel: 'LEAN MASS',
    value: '96.1',
    unit: 'lb',
    status: 'review',
    eligible: false,
  },
  {
    id: 'density',
    reportId: 'dexa',
    kind: 'Test results',
    label: 'Bone mineral density',
    originalLabel: 'BMD',
    value: '1.084',
    unit: 'g/cm²',
    status: 'review',
    eligible: false,
  },
  {
    id: 'glasses',
    reportId: 'vision',
    kind: 'Vision',
    label: 'Eyeglass prescription',
    originalLabel: 'DISTANCE RX',
    value: 'OD −1.25 / OS −1.00',
    unit: 'SPH',
    status: 'review',
    eligible: false,
  },
  {
    id: 'visit-note',
    reportId: 'visit',
    kind: 'Documents',
    label: 'Annual exam summary',
    originalLabel: 'ASSESSMENT',
    value: 'Preventive care discussed',
    status: 'review',
    eligible: true,
  },
  {
    id: 'person',
    reportId: 'visit',
    kind: 'People',
    label: 'Dr. Mira Santos',
    originalLabel: 'SEEN BY',
    value: 'Primary care clinician',
    status: 'review',
    eligible: true,
  },
  {
    id: 'medication',
    reportId: 'visit',
    kind: 'Prescriptions',
    label: 'Vitamin D3',
    originalLabel: 'CURRENT MEDICATIONS',
    value: '1,000',
    unit: 'IU daily',
    status: 'review',
    eligible: true,
  },
  {
    id: 'procedure',
    reportId: 'visit',
    kind: 'Procedures',
    label: 'Blood pressure screening',
    originalLabel: 'PROCEDURE',
    value: 'Completed',
    status: 'review',
    eligible: true,
  },
  {
    id: 'vitd',
    reportId: 'labs',
    kind: 'Test results',
    label: 'Vitamin D',
    originalLabel: '25-OH VITAMIN D',
    value: '39',
    unit: 'ng/mL',
    status: 'later',
    eligible: true,
  },
];
